"""remove_animal_qr_code

Revision ID: 3049c9c516c2
Revises: 628523691c25
Create Date: 2026-03-05 21:23:24.592176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3049c9c516c2'
down_revision: Union[str, None] = '628523691c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'qr_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
