"""add_device_qr_code

Revision ID: 628523691c25
Revises: 
Create Date: 2026-03-05 21:20:52.265983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '628523691c25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('qr_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'qr_code')
    # ### end Alembic commands ###
